name: hub
services:
  # Твой Postgres 18
  postgres:
    image: postgres:18
    container_name: hub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: hub_user
      POSTGRES_PASSWORD: hub_password
      POSTGRES_DB: hub_db 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - hub_network

  # Твой Redis 8.6
  redis:
    image: redis:8.6
    container_name: hub-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hub_network

  # Твоя Apache Kafka 4.3.0 (с родными переменными окружения)
  kafka:
    image: apache/kafka:4.3.0
    container_name: hub-kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - hub_network

  # Графический интерфейс для Kafka (выровнен по левому краю)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: hub-kafka-ui
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=Hub-Local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - hub_network

  # Твой Nginx Gateway
  nginx:
    image: nginx:alpine
    container_name: hub-nginx
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - hub_network

  identity-api:
    build:
      context: ../Hub.Identity.API  # Docker выходит из инфраструктуры и идет в репозиторий сервиса
      dockerfile: Dockerfile
    container_name: hub-identity-api
    restart: unless-stopped
    ports:
      - "5192:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=Identity_db;Username=hub_user;Password=hub_password
    depends_on:
      - postgres
    networks:
      - hub_network
      
networks:
  hub_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  kafka_data: