worker_processes 1;

events {
    worker_connections 1024;
}

http {
    server {
        # Порт, на котором Nginx будет слушать запросы
        listen 8080;

        # Маршрут для Identity API
        location /identity/ {
            # Важно: слеш в конце отрезает префикс /identity/ при передаче запроса
            proxy_pass http://host.docker.internal:5192/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Маршрут для VehicleLog API
        location /vehicle/ {
            proxy_pass http://host.docker.internal:5095/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}