http {
    upstream identity {
        server identity-api:80;
    }
    upstream filevault {
        server filevault-api:80;
    }

    server {
        listen 8080;

        location /api/auth/ {
            proxy_pass http://identity/api/auth/;
        }
        location /api/files/ {
            proxy_pass http://filevault/api/files/;
        }
        # … остальные маршруты
    }
}